### ISSUE TITLE
Training Something-Something datasets with horizontal flipping

### ISSUE THREAD

**Issue by boy860521** [arunos728/MotionSqueeze#1]
Hi~ thanks for sharing this fine work!
However, I found out that the code train the model with horizontal flipping, which in my opinion,  is not ideal for Something-Something datasets because of the "left right" instances. Have you tested whether it would affect or not?

**Comment by KimManjin** [comment]
Yes, as you pointed out, the horizontal flipping is not ideal for certain classes, such as ''pulling something from left to right," in SSv1,2 datasets. We updated our code to flip only video samples of which class do NOT include any 'left' or 'right' words.
We found that the updated flipping augmentation method improved top-1 accuracy as 0.5% (45.5%, paper -> 46.0%, now).
