### ISSUE TITLE
About LICENSE

### ISSUE THREAD

**Issue by yukkyo** [arunos728/MotionSqueeze#17]
Thanks for sharing the great code! :)

What is the license for this code?
I would also like to try this code in competitions.

**Comment by arunos728** [comment]
We follow the code of TSN-PyTorch (https://github.com/yjxiong/tsn-pytorch).
That code uses the BSD 2-Clause License for the code.

**Comment by yukkyo** [comment]
@arunos728 
Thanks for the reply!
I will try this code :)

Also, I would appreciate it if you could add LICENSE to the code. ([how to add license to repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository))
