### ISSUE TITLE
Too many typos in released codes...

### ISSUE THREAD

**Issue by Phoenix1327** [arunos728/MotionSqueeze#2]
https://github.com/arunos728/MotionSqueeze/blob/498d48a73f374180739b44a1db06aceac25f144c/resnet_TSM.py#L170
https://github.com/arunos728/MotionSqueeze/blob/498d48a73f374180739b44a1db06aceac25f144c/resnet_TSM.py#L175
https://github.com/arunos728/MotionSqueeze/blob/498d48a73f374180739b44a1db06aceac25f144c/resnet_TSM.py#L254

**Comment by Phoenix1327** [comment]
I think the authors should make sure the codes are correct and the results can be reproduced before you release them.

**Comment by KimManjin** [comment]
First of all, we feel sorry for the code errors.
We fixed the errors that you pointed out, and then we found the top-1 accuracy as 46.0% for MSNet R-18.

**Comment by Phoenix1327** [comment]
Thanks for your response and prompt updates.
