### ISSUE TITLE
Missing spatial_correlation_sampler file

### ISSUE THREAD

**Issue by spireheat** [arunos728/MotionSqueeze#3]
Can not import SpatialCorrelationSampler from spatial_correlation_sampler.

**Comment by KimManjin** [comment]
Hi,

You need to compile SpatialCorrelationSampler first to run our code properly.
Here is a [link](https://github.com/ClementPinard/Pytorch-Correlation-extension) to the C++/Pytorch implementation of Correlation module.

Please check compatibility issues before you compile the module.
I recommend you to make your environment as same as ours.

Thanks.
